### ISSUE TITLE
Hashtags in config queries

### ISSUE THREAD

**Issue by impshum** [buluba89/Yatcobot#20]
They're getting commented out. Can we have them as a "enclosed" string please?

**Comment by buluba89** [comment]
@impshum 
Hello thanks for reporting this issue

You can use strings like this:

``` yaml
  search:
    queries:
      - "retweet giveaway":
        lang: en
      - "giveaway retweet friend"
```
Maybe i should add this in documentation :P
